package org.me.education;
// Generated Apr 29, 2014 12:27:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,schema="public"
)
public class Course  implements java.io.Serializable {


     private int id;
     private String title;
     private String level;
     private String format;
     private String description;
     private char status;
     private String CCode;
     private Set takeses = new HashSet(0);

    public Course() {
    }

	
    public Course(int id, String title, String level, String format, String description, char status, String CCode) {
        this.id = id;
        this.title = title;
        this.level = level;
        this.format = format;
        this.description = description;
        this.status = status;
        this.CCode = CCode;
    }
    public Course(int id, String title, String level, String format, String description, char status, String CCode, Set takeses) {
       this.id = id;
       this.title = title;
       this.level = level;
       this.format = format;
       this.description = description;
       this.status = status;
       this.CCode = CCode;
       this.takeses = takeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="level", nullable=false, length=12)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    
    @Column(name="format", nullable=false, length=32)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="status", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }

    
    @Column(name="c_code", nullable=false, length=32)
    public String getCCode() {
        return this.CCode;
    }
    
    public void setCCode(String CCode) {
        this.CCode = CCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set getTakeses() {
        return this.takeses;
    }
    
    public void setTakeses(Set takeses) {
        this.takeses = takeses;
    }




}


