package com.education;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Certificate generated by hbm2java
 */
public class Certificate  implements java.io.Serializable {


     private int id;
     private String cerCode;
     private String title;
     private String description;
     private Date expireDate;
     private String issuedBy;
     private String TCode;

    public Certificate() {
    }

	
    public Certificate(int id, String cerCode, String title, String description, String issuedBy) {
        this.id = id;
        this.cerCode = cerCode;
        this.title = title;
        this.description = description;
        this.issuedBy = issuedBy;
    }
    public Certificate(int id, String cerCode, String title, String description, Date expireDate, String issuedBy, String TCode) {
       this.id = id;
       this.cerCode = cerCode;
       this.title = title;
       this.description = description;
       this.expireDate = expireDate;
       this.issuedBy = issuedBy;
       this.TCode = TCode;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCerCode() {
        return this.cerCode;
    }
    
    public void setCerCode(String cerCode) {
        this.cerCode = cerCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public String getIssuedBy() {
        return this.issuedBy;
    }
    
    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }
    public String getTCode() {
        return this.TCode;
    }
    
    public void setTCode(String TCode) {
        this.TCode = TCode;
    }




}


