package com.education;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int id;
     private String title;
     private String level;
     private String format;
     private String description;
     private char status;
     private String CCode;
     private Set takeses = new HashSet(0);

    public Course() {
    }

	
    public Course(int id, String title, String level, String format, String description, char status, String CCode) {
        this.id = id;
        this.title = title;
        this.level = level;
        this.format = format;
        this.description = description;
        this.status = status;
        this.CCode = CCode;
    }
    public Course(int id, String title, String level, String format, String description, char status, String CCode, Set takeses) {
       this.id = id;
       this.title = title;
       this.level = level;
       this.format = format;
       this.description = description;
       this.status = status;
       this.CCode = CCode;
       this.takeses = takeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public String getCCode() {
        return this.CCode;
    }
    
    public void setCCode(String CCode) {
        this.CCode = CCode;
    }
    public Set getTakeses() {
        return this.takeses;
    }
    
    public void setTakeses(Set takeses) {
        this.takeses = takeses;
    }




}


