package com.education;
// Generated Apr 6, 2014 6:09:43 PM by Hibernate Tools 3.6.0



/**
 * EducInstitute generated by hbm2java
 */
public class EducInstitute  implements java.io.Serializable {


     private int id;
     private String name;

    public EducInstitute() {
    }

    public EducInstitute(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


