package com.education;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * EducInstitute generated by hbm2java
 */
public class EducInstitute  implements java.io.Serializable {


     private int id;
     private String name;
     private Set sections = new HashSet(0);

    public EducInstitute() {
    }

	
    public EducInstitute(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public EducInstitute(int id, String name, Set sections) {
       this.id = id;
       this.name = name;
       this.sections = sections;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSections() {
        return this.sections;
    }
    
    public void setSections(Set sections) {
        this.sections = sections;
    }




}


