package com.education;
// Generated Apr 6, 2014 6:09:43 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private int id;
     private int courseId;
     private Date startDate;
     private Date endDate;
     private String format;
     private String offeredBy;
     private BigDecimal cost;
     private char status;

    public Section() {
    }

    public Section(int id, int courseId, Date startDate, Date endDate, String format, String offeredBy, BigDecimal cost, char status) {
       this.id = id;
       this.courseId = courseId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.format = format;
       this.offeredBy = offeredBy;
       this.cost = cost;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getOfferedBy() {
        return this.offeredBy;
    }
    
    public void setOfferedBy(String offeredBy) {
        this.offeredBy = offeredBy;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }




}


