package com.education;
// Generated Apr 8, 2014 12:02:02 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name="section"
    ,schema="public"
)
public class Section  implements java.io.Serializable {


     private int id;
     private int courseId;
     private Date startDate;
     private Date endDate;
     private String format;
     private String offeredBy;
     private BigDecimal cost;
     private char status;
     private Set<EducInstitute> educInstitutes = new HashSet<EducInstitute>(0);
     private Set<Takes> takeses = new HashSet<Takes>(0);

    public Section() {
    }

	
    public Section(int id, int courseId, Date startDate, Date endDate, String format, String offeredBy, BigDecimal cost, char status) {
        this.id = id;
        this.courseId = courseId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.format = format;
        this.offeredBy = offeredBy;
        this.cost = cost;
        this.status = status;
    }
    public Section(int id, int courseId, Date startDate, Date endDate, String format, String offeredBy, BigDecimal cost, char status, Set<EducInstitute> educInstitutes, Set<Takes> takeses) {
       this.id = id;
       this.courseId = courseId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.format = format;
       this.offeredBy = offeredBy;
       this.cost = cost;
       this.status = status;
       this.educInstitutes = educInstitutes;
       this.takeses = takeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="course_id", nullable=false)
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=13)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=13)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="format", nullable=false, length=32)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="offered_by", nullable=false)
    public String getOfferedBy() {
        return this.offeredBy;
    }
    
    public void setOfferedBy(String offeredBy) {
        this.offeredBy = offeredBy;
    }

    
    @Column(name="cost", nullable=false, precision=12)
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    
    @Column(name="status", nullable=false, length=1)
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="offers_course", schema="public", joinColumns = { 
        @JoinColumn(name="section_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="educ_institute_id", nullable=false, updatable=false) })
    public Set<EducInstitute> getEducInstitutes() {
        return this.educInstitutes;
    }
    
    public void setEducInstitutes(Set<EducInstitute> educInstitutes) {
        this.educInstitutes = educInstitutes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="section")
    public Set<Takes> getTakeses() {
        return this.takeses;
    }
    
    public void setTakeses(Set<Takes> takeses) {
        this.takeses = takeses;
    }




}


