package com.education;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private int id;
     private int courseId;
     private Date startDate;
     private Date endDate;
     private String format;
     private String offeredBy;
     private BigDecimal cost;
     private char status;
     private Set educInstitutes = new HashSet(0);
     private Set takeses = new HashSet(0);

    public Section() {
    }

	
    public Section(int id, int courseId, Date startDate, Date endDate, String format, String offeredBy, BigDecimal cost, char status) {
        this.id = id;
        this.courseId = courseId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.format = format;
        this.offeredBy = offeredBy;
        this.cost = cost;
        this.status = status;
    }
    public Section(int id, int courseId, Date startDate, Date endDate, String format, String offeredBy, BigDecimal cost, char status, Set educInstitutes, Set takeses) {
       this.id = id;
       this.courseId = courseId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.format = format;
       this.offeredBy = offeredBy;
       this.cost = cost;
       this.status = status;
       this.educInstitutes = educInstitutes;
       this.takeses = takeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getOfferedBy() {
        return this.offeredBy;
    }
    
    public void setOfferedBy(String offeredBy) {
        this.offeredBy = offeredBy;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public Set getEducInstitutes() {
        return this.educInstitutes;
    }
    
    public void setEducInstitutes(Set educInstitutes) {
        this.educInstitutes = educInstitutes;
    }
    public Set getTakeses() {
        return this.takeses;
    }
    
    public void setTakeses(Set takeses) {
        this.takeses = takeses;
    }




}


