package com.education;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import com.jobseeker.Person;
import java.math.BigDecimal;

/**
 * Takes generated by hbm2java
 */
public class Takes  implements java.io.Serializable {


     private TakesId id;
     private Course course;
     private Section section;
     private Person person;
     private boolean paid;
     private BigDecimal grade;

    public Takes() {
    }

    public Takes(TakesId id, Course course, Section section, Person person, boolean paid, BigDecimal grade) {
       this.id = id;
       this.course = course;
       this.section = section;
       this.person = person;
       this.paid = paid;
       this.grade = grade;
    }
   
    public TakesId getId() {
        return this.id;
    }
    
    public void setId(TakesId id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }
    public BigDecimal getGrade() {
        return this.grade;
    }
    
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }




}


