package org.me.details;
// Generated May 1, 2014 1:30:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,schema="public"
)
public class Address  implements java.io.Serializable {


     private int id;
     private String address1;
     private String address2;
     private String city;
     private String zip;
     private String state;
     private String county;
     private String country;
     private Set persons = new HashSet(0);
     private Set companies = new HashSet(0);

    public Address() {
    }

	
    public Address(int id, String address1, String city, String zip, String state) {
        this.id = id;
        this.address1 = address1;
        this.city = city;
        this.zip = zip;
        this.state = state;
    }
    public Address(int id, String address1, String address2, String city, String zip, String state, String county, String country, Set persons, Set companies) {
       this.id = id;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.zip = zip;
       this.state = state;
       this.county = county;
       this.country = country;
       this.persons = persons;
       this.companies = companies;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="address_1", nullable=false, length=64)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="address_2", length=64)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="city", nullable=false, length=64)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="zip", nullable=false, length=12)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="state", nullable=false, length=32)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="county", length=32)
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }

    
    @Column(name="country", length=64)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }




}


