package org.me.education;
// Generated May 1, 2014 1:30:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Certificate generated by hbm2java
 */
@Entity
@Table(name="certificate"
    ,schema="public"
)
public class Certificate  implements java.io.Serializable {


     private int id;
     private String cerCode;
     private String title;
     private String description;
     private Date expireDate;
     private String issuedBy;
     private String TCode;

    public Certificate() {
    }

	
    public Certificate(int id, String cerCode, String title, String description, String issuedBy) {
        this.id = id;
        this.cerCode = cerCode;
        this.title = title;
        this.description = description;
        this.issuedBy = issuedBy;
    }
    public Certificate(int id, String cerCode, String title, String description, Date expireDate, String issuedBy, String TCode) {
       this.id = id;
       this.cerCode = cerCode;
       this.title = title;
       this.description = description;
       this.expireDate = expireDate;
       this.issuedBy = issuedBy;
       this.TCode = TCode;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cer_code", nullable=false, length=32)
    public String getCerCode() {
        return this.cerCode;
    }
    
    public void setCerCode(String cerCode) {
        this.cerCode = cerCode;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expire_date", length=13)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    
    @Column(name="issued_by", nullable=false)
    public String getIssuedBy() {
        return this.issuedBy;
    }
    
    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }

    
    @Column(name="t_code", length=32)
    public String getTCode() {
        return this.TCode;
    }
    
    public void setTCode(String TCode) {
        this.TCode = TCode;
    }




}


