<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://employerServices.me.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="JobMarketReporting" targetNamespace="http://employerServices.me.org/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://employerServices.me.org/" elementFormDefault="unqualified" targetNamespace="http://employerServices.me.org/" version="1.0">

  <xs:element name="getMostDesiredCreds" type="tns:getMostDesiredCreds"/>

  <xs:element name="getMostDesiredCredsResponse" type="tns:getMostDesiredCredsResponse"/>

  <xs:complexType name="getMostDesiredCreds">
    <xs:sequence>
      <xs:element minOccurs="0" name="occupation" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getMostDesiredCredsResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getMostDesiredCredsResponse">
    <wsdl:part element="tns:getMostDesiredCredsResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getMostDesiredCreds">
    <wsdl:part element="tns:getMostDesiredCreds" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="JobMarketReporting">
    <wsdl:operation name="getMostDesiredCreds">
      <wsdl:input message="tns:getMostDesiredCreds" name="getMostDesiredCreds">
    </wsdl:input>
      <wsdl:output message="tns:getMostDesiredCredsResponse" name="getMostDesiredCredsResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="JobMarketReportingSoapBinding" type="tns:JobMarketReporting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getMostDesiredCreds">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getMostDesiredCreds">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getMostDesiredCredsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="JobMarketReporting">
    <wsdl:port binding="tns:JobMarketReportingSoapBinding" name="JobMarketReportingPort">
      <soap:address location="http://localhost:8080/JobSeekerWS/JobMarketReporting"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>