package com.jobseeker;
// Generated Apr 6, 2014 6:09:43 PM by Hibernate Tools 3.6.0



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private PersonId id;

    public Person() {
    }

    public Person(PersonId id) {
       this.id = id;
    }
   
    public PersonId getId() {
        return this.id;
    }
    
    public void setId(PersonId id) {
        this.id = id;
    }




}


