package com.jobseeker;
// Generated Apr 6, 2014 6:09:43 PM by Hibernate Tools 3.6.0



/**
 * PersonId generated by hbm2java
 */
public class PersonId  implements java.io.Serializable {


     private String name;
     private Integer addressId;
     private String zipCode;
     private String email;
     private Character gender;
     private int id;

    public PersonId() {
    }

	
    public PersonId(String name, int id) {
        this.name = name;
        this.id = id;
    }
    public PersonId(String name, Integer addressId, String zipCode, String email, Character gender, int id) {
       this.name = name;
       this.addressId = addressId;
       this.zipCode = zipCode;
       this.email = email;
       this.gender = gender;
       this.id = id;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonId) ) return false;
		 PersonId castOther = ( PersonId ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getAddressId()==castOther.getAddressId()) || ( this.getAddressId()!=null && castOther.getAddressId()!=null && this.getAddressId().equals(castOther.getAddressId()) ) )
 && ( (this.getZipCode()==castOther.getZipCode()) || ( this.getZipCode()!=null && castOther.getZipCode()!=null && this.getZipCode().equals(castOther.getZipCode()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getGender()==castOther.getGender()) || ( this.getGender()!=null && castOther.getGender()!=null && this.getGender().equals(castOther.getGender()) ) )
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getAddressId() == null ? 0 : this.getAddressId().hashCode() );
         result = 37 * result + ( getZipCode() == null ? 0 : this.getZipCode().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
         result = 37 * result + this.getId();
         return result;
   }   


}


