package com.jobseeker;
// Generated Apr 6, 2014 6:32:32 PM by Hibernate Tools 3.6.0



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer addressId;
     private String zipCode;
     private String email;
     private Character gender;

    public Person() {
    }

	
    public Person(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Person(int id, String name, Integer addressId, String zipCode, String email, Character gender) {
       this.id = id;
       this.name = name;
       this.addressId = addressId;
       this.zipCode = zipCode;
       this.email = email;
       this.gender = gender;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }




}


