package com.employer;
// Generated Apr 8, 2014 12:02:02 AM by Hibernate Tools 3.6.0


import com.jobseeker.Person;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Applies generated by hbm2java
 */
@Entity
@Table(name="applies"
    ,schema="public"
)
public class Applies  implements java.io.Serializable {


     private AppliesId id;
     private Job job;
     private Person person;
     private boolean approved;

    public Applies() {
    }

    public Applies(AppliesId id, Job job, Person person, boolean approved) {
       this.id = id;
       this.job = job;
       this.person = person;
       this.approved = approved;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="personId", column=@Column(name="person_id", nullable=false) ), 
        @AttributeOverride(name="jobId", column=@Column(name="job_id", nullable=false) ) } )
    public AppliesId getId() {
        return this.id;
    }
    
    public void setId(AppliesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_id", nullable=false, insertable=false, updatable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false, insertable=false, updatable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    
    @Column(name="approved", nullable=false)
    public boolean isApproved() {
        return this.approved;
    }
    
    public void setApproved(boolean approved) {
        this.approved = approved;
    }




}


