package com.employer;
// Generated Apr 8, 2014 12:02:02 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppliesId generated by hbm2java
 */
@Embeddable
public class AppliesId  implements java.io.Serializable {


     private int personId;
     private int jobId;

    public AppliesId() {
    }

    public AppliesId(int personId, int jobId) {
       this.personId = personId;
       this.jobId = jobId;
    }
   


    @Column(name="person_id", nullable=false)
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }


    @Column(name="job_id", nullable=false)
    public int getJobId() {
        return this.jobId;
    }
    
    public void setJobId(int jobId) {
        this.jobId = jobId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppliesId) ) return false;
		 AppliesId castOther = ( AppliesId ) other; 
         
		 return (this.getPersonId()==castOther.getPersonId())
 && (this.getJobId()==castOther.getJobId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPersonId();
         result = 37 * result + this.getJobId();
         return result;
   }   


}


