package com.employer;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import com.jobseeker.Person;

/**
 * Applies generated by hbm2java
 */
public class Applies  implements java.io.Serializable {


     private AppliesId id;
     private Job job;
     private Person person;
     private boolean approved;

    public Applies() {
    }

    public Applies(AppliesId id, Job job, Person person, boolean approved) {
       this.id = id;
       this.job = job;
       this.person = person;
       this.approved = approved;
    }
   
    public AppliesId getId() {
        return this.id;
    }
    
    public void setId(AppliesId id) {
        this.id = id;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public boolean isApproved() {
        return this.approved;
    }
    
    public void setApproved(boolean approved) {
        this.approved = approved;
    }




}


