package com.employer;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private int id;
     private Company company;
     private Position position;
     private String jobCode;
     private String type;
     private String payType;
     private String payRate;
     private Set applieses = new HashSet(0);

    public Job() {
    }

	
    public Job(int id, Company company, Position position, String jobCode, String type, String payType, String payRate) {
        this.id = id;
        this.company = company;
        this.position = position;
        this.jobCode = jobCode;
        this.type = type;
        this.payType = payType;
        this.payRate = payRate;
    }
    public Job(int id, Company company, Position position, String jobCode, String type, String payType, String payRate, Set applieses) {
       this.id = id;
       this.company = company;
       this.position = position;
       this.jobCode = jobCode;
       this.type = type;
       this.payType = payType;
       this.payRate = payRate;
       this.applieses = applieses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public Position getPosition() {
        return this.position;
    }
    
    public void setPosition(Position position) {
        this.position = position;
    }
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getPayType() {
        return this.payType;
    }
    
    public void setPayType(String payType) {
        this.payType = payType;
    }
    public String getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(String payRate) {
        this.payRate = payRate;
    }
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }




}


