package com.employer;
// Generated Apr 6, 2014 6:32:32 PM by Hibernate Tools 3.6.0



/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private int id;
     private String jobCode;
     private int posId;
     private String type;
     private String payType;
     private String payRate;
     private int companyId;

    public Job() {
    }

    public Job(int id, String jobCode, int posId, String type, String payType, String payRate, int companyId) {
       this.id = id;
       this.jobCode = jobCode;
       this.posId = posId;
       this.type = type;
       this.payType = payType;
       this.payRate = payRate;
       this.companyId = companyId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }
    public int getPosId() {
        return this.posId;
    }
    
    public void setPosId(int posId) {
        this.posId = posId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getPayType() {
        return this.payType;
    }
    
    public void setPayType(String payType) {
        this.payType = payType;
    }
    public String getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(String payRate) {
        this.payRate = payRate;
    }
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }




}


