package com.employer;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position  implements java.io.Serializable {


     private int id;
     private String posCode;
     private String title;
     private String description;
     private String basePayType;
     private BigDecimal basePay;
     private Set jobs = new HashSet(0);
     private Set knowledgeSkills = new HashSet(0);

    public Position() {
    }

	
    public Position(int id, String posCode, String title, String basePayType, BigDecimal basePay) {
        this.id = id;
        this.posCode = posCode;
        this.title = title;
        this.basePayType = basePayType;
        this.basePay = basePay;
    }
    public Position(int id, String posCode, String title, String description, String basePayType, BigDecimal basePay, Set jobs, Set knowledgeSkills) {
       this.id = id;
       this.posCode = posCode;
       this.title = title;
       this.description = description;
       this.basePayType = basePayType;
       this.basePay = basePay;
       this.jobs = jobs;
       this.knowledgeSkills = knowledgeSkills;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPosCode() {
        return this.posCode;
    }
    
    public void setPosCode(String posCode) {
        this.posCode = posCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBasePayType() {
        return this.basePayType;
    }
    
    public void setBasePayType(String basePayType) {
        this.basePayType = basePayType;
    }
    public BigDecimal getBasePay() {
        return this.basePay;
    }
    
    public void setBasePay(BigDecimal basePay) {
        this.basePay = basePay;
    }
    public Set getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Set jobs) {
        this.jobs = jobs;
    }
    public Set getKnowledgeSkills() {
        return this.knowledgeSkills;
    }
    
    public void setKnowledgeSkills(Set knowledgeSkills) {
        this.knowledgeSkills = knowledgeSkills;
    }




}


