package org.me.lookups;
// Generated Apr 29, 2014 12:27:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * KnowledgeSkill generated by hbm2java
 */
@Entity
@Table(name="mos_code"
    ,schema="public"
)
public class MOS implements java.io.Serializable {


    private int id;
    private String mos;
    private String title;
    private String branch;
     
     public MOS() {
    }

	
    public MOS(int id, String branch, String title, String mos) {
        this.id = id;
        this.mos = mos;
        this.title = title;
        this.branch = branch;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="mos", nullable=false, length=32)
    public String getmos() {
        return this.mos;
    }
    
    public void setmos(String mos) {
        this.mos = mos;
    }

    @Column(name="branch", nullable = false, length = 12)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    
    @Column(name="title", nullable = false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
}


