package org.me.lookups;
// Generated Apr 29, 2014 12:27:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * KnowledgeSkill generated by hbm2java
 */
@Entity
@Table(name="mos_civ_lk"
    ,schema="public"
)
public class MOS_CIV_LK  implements java.io.Serializable {


     private int id;
     private int mos_code;
     private int civ_code;    
     
     public MOS_CIV_LK() {
    }

	
    public MOS_CIV_LK(int id, int mos_code, int civ_code) {
        this.id = id;
        this.mos_code = mos_code;
        this.civ_code = civ_code;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="mos_code", nullable=false)
    public int getmos_code() {
        return this.mos_code;
    }
    
    public void setmos_code(int mos_code) {
        this.mos_code = mos_code;
    }

    @Column(name="civ_code", nullable=false)
    public int getciv_code() {
        return this.civ_code;
    }
    
    public void setciv_code(int civ_code) {
        this.civ_code = civ_code;
    }
    
}





