package com.skill;
// Generated Apr 7, 2014 9:30:24 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * KnowledgeSkill generated by hbm2java
 */
public class KnowledgeSkill  implements java.io.Serializable {


     private int id;
     private String ksCode;
     private String title;
     private String description;
     private String level;
     private Set positions = new HashSet(0);

    public KnowledgeSkill() {
    }

	
    public KnowledgeSkill(int id, String ksCode, String title, String description, String level) {
        this.id = id;
        this.ksCode = ksCode;
        this.title = title;
        this.description = description;
        this.level = level;
    }
    public KnowledgeSkill(int id, String ksCode, String title, String description, String level, Set positions) {
       this.id = id;
       this.ksCode = ksCode;
       this.title = title;
       this.description = description;
       this.level = level;
       this.positions = positions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKsCode() {
        return this.ksCode;
    }
    
    public void setKsCode(String ksCode) {
        this.ksCode = ksCode;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    public Set getPositions() {
        return this.positions;
    }
    
    public void setPositions(Set positions) {
        this.positions = positions;
    }




}


