package com.skill;
// Generated Apr 8, 2014 12:02:02 AM by Hibernate Tools 3.6.0


import com.employer.Position;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * KnowledgeSkill generated by hbm2java
 */
@Entity
@Table(name="knowledge_skill"
    ,schema="public"
)
public class KnowledgeSkill  implements java.io.Serializable {


     private int id;
     private String ksCode;
     private String title;
     private String description;
     private String level;
     private Set<Position> positions = new HashSet<Position>(0);

    public KnowledgeSkill() {
    }

	
    public KnowledgeSkill(int id, String ksCode, String title, String description, String level) {
        this.id = id;
        this.ksCode = ksCode;
        this.title = title;
        this.description = description;
        this.level = level;
    }
    public KnowledgeSkill(int id, String ksCode, String title, String description, String level, Set<Position> positions) {
       this.id = id;
       this.ksCode = ksCode;
       this.title = title;
       this.description = description;
       this.level = level;
       this.positions = positions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ks_code", nullable=false, length=32)
    public String getKsCode() {
        return this.ksCode;
    }
    
    public void setKsCode(String ksCode) {
        this.ksCode = ksCode;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="level", nullable=false, length=12)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="position_req_skills", schema="public", joinColumns = { 
        @JoinColumn(name="skill_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="position_id", nullable=false, updatable=false) })
    public Set<Position> getPositions() {
        return this.positions;
    }
    
    public void setPositions(Set<Position> positions) {
        this.positions = positions;
    }




}


