package org.me.jobseeker;
// Generated Apr 29, 2014 12:27:08 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.me.details.Address;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,schema="public"
)
public class Person  implements java.io.Serializable {


     private int id;
     private Address address;
     private String name;
     private String zipCode;
     private String email;
     private Character gender;
     private Set applieses = new HashSet(0);
     private Set takeses = new HashSet(0);

    public Person() {
    }

	
    public Person(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Person(int id, Address address, String name, String zipCode, String email, Character gender, Set applieses, Set takeses) {
       this.id = id;
       this.address = address;
       this.name = name;
       this.zipCode = zipCode;
       this.email = email;
       this.gender = gender;
       this.applieses = applieses;
       this.takeses = takeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_id")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="zip_code", length=12)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set getTakeses() {
        return this.takeses;
    }
    
    public void setTakeses(Set takeses) {
        this.takeses = takeses;
    }




}


