package org.me.users;
// Generated May 1, 2014 1:30:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name="user_profile"
    ,schema="public"
)
public class UserProfile  implements java.io.Serializable {


     private int id;
     private String usr;
     private String psw;
     private String type;
     private Set companies = new HashSet(0);
     private Set persons = new HashSet(0);
     private Set educInstitutes = new HashSet(0);

    public UserProfile() {
    }

	
    public UserProfile(int id, String usr, String psw, String type) {
        this.id = id;
        this.usr = usr;
        this.psw = psw;
        this.type = type;
    }
    public UserProfile(int id, String usr, String psw, String type, Set companies, Set persons, Set educInstitutes) {
       this.id = id;
       this.usr = usr;
       this.psw = psw;
       this.type = type;
       this.companies = companies;
       this.persons = persons;
       this.educInstitutes = educInstitutes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="usr", nullable=false)
    public String getUsr() {
        return this.usr;
    }
    
    public void setUsr(String usr) {
        this.usr = usr;
    }

    
    @Column(name="psw", nullable=false)
    public String getPsw() {
        return this.psw;
    }
    
    public void setPsw(String psw) {
        this.psw = psw;
    }

    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_company_map", schema="public", uniqueConstraints={@UniqueConstraint(columnNames="company_id"), @UniqueConstraint(columnNames="user_id")}, joinColumns = { 
        @JoinColumn(name="user_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="company_id", unique=true, nullable=false, updatable=false) })
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_person_map", schema="public", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="person_id", nullable=false, updatable=false) })
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_educ_map", schema="public", uniqueConstraints={@UniqueConstraint(columnNames="educ_id"), @UniqueConstraint(columnNames="user_id")}, joinColumns = { 
        @JoinColumn(name="user_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="educ_id", unique=true, nullable=false, updatable=false) })
    public Set getEducInstitutes() {
        return this.educInstitutes;
    }
    
    public void setEducInstitutes(Set educInstitutes) {
        this.educInstitutes = educInstitutes;
    }




}


