package org.me.employer;
// Generated May 1, 2014 1:30:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.me.details.Address;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name="company"
    ,schema="public"
)
public class Company  implements java.io.Serializable {


     private int id;
     private Address address;
     private String name;
     private String email;
     private Set userProfiles = new HashSet(0);
     private Set jobs = new HashSet(0);

    public Company() {
    }

	
    public Company(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Company(int id, Address address, String name, String email, Set userProfiles, Set jobs) {
       this.id = id;
       this.address = address;
       this.name = name;
       this.email = email;
       this.userProfiles = userProfiles;
       this.jobs = jobs;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_id")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_company_map", schema="public", uniqueConstraints={@UniqueConstraint(columnNames="company_id"), @UniqueConstraint(columnNames="user_id")}, joinColumns = { 
        @JoinColumn(name="company_id", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", unique=true, nullable=false, updatable=false) })
    public Set getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set userProfiles) {
        this.userProfiles = userProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="company")
    public Set getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Set jobs) {
        this.jobs = jobs;
    }




}


