package org.me.employer;
// Generated May 1, 2014 1:30:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name="job"
    ,schema="public"
)
public class Job  implements java.io.Serializable {


     private int id;
     private Position position;
     private Company company;
     private String jobCode;
     private String type;
     private String payType;
     private String payRate;
     private Set applieses = new HashSet(0);

    public Job() {
    }

	
    public Job(int id, Position position, Company company, String jobCode, String type, String payType, String payRate) {
        this.id = id;
        this.position = position;
        this.company = company;
        this.jobCode = jobCode;
        this.type = type;
        this.payType = payType;
        this.payRate = payRate;
    }
    public Job(int id, Position position, Company company, String jobCode, String type, String payType, String payRate, Set applieses) {
       this.id = id;
       this.position = position;
       this.company = company;
       this.jobCode = jobCode;
       this.type = type;
       this.payType = payType;
       this.payRate = payRate;
       this.applieses = applieses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="position_id", nullable=false)
    public Position getPosition() {
        return this.position;
    }
    
    public void setPosition(Position position) {
        this.position = position;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="job_code", nullable=false, length=32)
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    
    @Column(name="type", nullable=false, length=12)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="pay_type", nullable=false, length=12)
    public String getPayType() {
        return this.payType;
    }
    
    public void setPayType(String payType) {
        this.payType = payType;
    }

    
    @Column(name="pay_rate", nullable=false, length=12)
    public String getPayRate() {
        return this.payRate;
    }
    
    public void setPayRate(String payRate) {
        this.payRate = payRate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }




}


